---
type: yml

application:
  graceful_shutdown_timeout_in_seconds: 10
  profiling_port: 1234
  enable_profiling: true
  read_header_timeout: 30

http_server:
  port: 8088

logger:
  filename: ./logs/log.json
  local_time: false
  max_size: 10
  max_backups: 1
  max_age: 1
  stdout_log_level: debug
  writer_log_level: debug